config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#welcome'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get  '/signup' => 'users#new'
  post '/logout' => 'sessions#destroy'
  
  get '/properties/search' => 'properties#search', :as =>'search_properties'

  get '/auth/google_oauth2/callback' => 'sessions#omniauth'

  patch '/landlord_or_tenant' => 'users#landlord_tenant'

  resources :users

  resources :tenants, only: [:show, :edit] do
    resources :properties, only: [:index] do
      resources :reviews, only: [:new, :edit, :update, :destroy, :show]
        post '/' => 'reviews#create'
        patch '/' => 'reviews#update'
        put '/' => 'reviews#update'
    end

    get '/properties/:id' => 'properties#tenant_property', :as => 'previous_property'
  end
  
  resources :landlords, only: [:show, :edit] do
    resources :properties, only: [:edit, :update, :new, :create, :destroy]
    get '/properties' => 'properties#landlord_properties', :as => 'properties_show'
    get '/properties/:id' => 'properties#landlord_property', :as => 'property_show'
  end

  resources :landlords, only: [:show, :edit, :update]

  resources :properties, only: [:index, :show]
   post '/properties' => 'properties#filter_properties', :as => 'filter_properties'
   
  

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_one :landlord, dependent: :destroy
    has_one :tenant, dependent: :destroy

    validates :email, uniqueness: true,  presence: true
    validates :first_name, :last_name, presence: true

    has_secure_password

    def name
        self.first_name + " " + self.last_name
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login, only: [:edit, :update, :destroy]
    before_action :find_user, only: [:edit, :update, :destroy]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            if @user.landlord_checkbox
                landlord = Landlord.create(user_id: @user.id)
                session[:landlord_id] = landlord.id 
                redirect_to landlord_path(landlord)
            else
                tenant = Tenant.create(user_id: @user.id)
                session[:tenant_id] = tenant.id 
                redirect_to tenant_path(tenant)
            end
        else
            render :new
        end
            
    end

    def edit
          if user_authorized?(@user)
             @edit = true 
             render :edit
          else 
            @user = User.find_by_id(session[:user_id])
            flash[:error] = "Not authorized to access this profile!"
            landlord_or_tenant_path
          end
       
    end

    def update
          if user_authorized?(@user)
             @user.update(user_params)
             landlord_or_tenant_path
          else
            @user = User.find_by_id(session[:user_id])
            flash[:error] = "Not authorized to access this profile!"

            landlord_or_tenant_path
          end
       
    end

    def landlord_tenant
        @user = User.find_by_id(session[:user_id])
        @user.update(landlord_tenant_params)
        if @user.landlord_checkbox
            landlord = Landlord.create(user_id: @user.id)
            session[:landlord_id] = landlord.id 
            redirect_to landlord_path(landlord)
        else
            tenant = Tenant.create(user_id: @user.id)
            session[:tenant_id] = tenant.id 
            redirect_to tenant_path(tenant)
        end
    end

    def destroy
          if user_authorized?(@user)
             if @user.tenant && @user.tenant.property
                    @user.tenant.property.tenant_id = nil 
                    @user.tenant.property.save
             end
             @user.destroy
             reset_session
             flash[:message] = "Account deleted."
             redirect_to root_path
          else
            @user = User.find_by_id(session[:user_id])
            flash[:error] = "Not authorized to access this profile!"

            landlord_or_tenant_path
          end
      
        
    end



    private
    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :bio, :image_url, :landlord_checkbox)
    end
   
    def landlord_tenant_params
        params.require(:user).permit(:landlord_checkbox)
    end
    

    def find_user
        @user = User.find_by_id(params[:id])
        if !@user 
            flash[:error] = "Profile was not found"
            landlord_or_tenant_path
        end
    end
end

app/views/users/_form.html.erb
<div class="vh-100 img-container" style="padding-top: 120px;">

<div class="card text-lightpink bg-lightpink mb-3 m-auto" style="max-width: 25rem;">
<%= render partial: 'layouts/errors', locals: {obj: @user} %>
<% if !@edit %>
<div class="card-body"><h1>Please Sign Up!</h1></div>
<% else %>
<div class="card-body"><h1>Edit Your Account</h1></div>
<% end %>
<div class="card-body">

<%= form_for @user  do |f| %>
  <%= f.label :first_name%><br>
  <%= f.text_field :first_name, :class => "border border-pink" %><br>
  <%= f.label :last_name %><br>
  <%= f.text_field :last_name, :class => "border border-pink" %><br>
  <%= f.label :email %><br>
  <%= f.text_field :email, :class => "border border-pink" %><br>
  <%= f.label :password %><br>
  <%= f.password_field :password, :class => "border border-pink" %><br>
  <%= f.label :bio %><br>
  <%= f.text_area :bio, :class => "border border-pink" %><br>
  <%= f.label :image_url %><br>
  <%= f.text_field :image_url, :class => "border border-pink" %><br>
  <% if !@edit %>
    <%= f.label :landlord_checkbox, "Check box if you are a landlord" %>
    <%= f.hidden_field :landlord_checkbox, :value => "0" %>
    <%= f.check_box :landlord_checkbox %><br>
  <% end %>
  <br>

  <%= f.submit :class => "text-decoration-none btn btn-outline-dark" %>
<% end %><br>
<p><%= link_to '<<', :back, :class => "back" %></p>
</div>
</div>
</div>

app/views/users/_show.html.erb
<nav>
            <ul class="nav justify-content-end p-2">
            <li class='nav-link' ><%= link_to "View All Available Properties", properties_path, class: 'nav-link'%></li>
            <% if @user.landlord %>
              <li class='nav-link'><%= link_to "Edit Account", edit_landlord_path(@user.landlord), class: 'nav-link' %></li>
            <% end %>
            <% if @user.tenant %>
              <li class='nav-link'><%= link_to "Edit Account", edit_tenant_path(@user.tenant), class: 'nav-link'  %></li>
            <% end %>
            <li class='nav-link'> <%= link_to "Delete Account", user_path(@user), method: :delete, class: 'nav-link' %></li>
            <li class='nav-link'> <%= link_to "Log Out", logout_path, method: "post", class: 'nav-link'%></li>
                
            </ul>
        
</nav>
<div class='pl-3 mt-n5'>
<h2>Hello, <%= @user.first_name %>!</h2>
<div class='pt-3'>
<p><%= image_tag  @user.image_url,  height:'250', width:'200' if @user.image_url %></p>

  <p><b>Full Name:</b> <%= @user.name %></p>  
  <p><b>Email:</b> <%= @user.email %></p>
  <p><b>Bio:</b> <%= @user.bio %></p>
  

</div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/new.html.erb
<%= render 'form' %>


 