config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#welcome'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get  '/signup' => 'users#new'
  post '/logout' => 'sessions#destroy'
  
  get '/properties/search' => 'properties#search', :as =>'search_properties'

  get '/auth/google_oauth2/callback' => 'sessions#omniauth'

  patch '/landlord_or_tenant' => 'users#landlord_tenant'

  resources :users

  resources :tenants, only: [:show, :edit] do
    resources :properties, only: [:index] do
      resources :reviews, only: [:new, :edit, :update, :destroy, :show]
        post '/' => 'reviews#create'
        patch '/' => 'reviews#update'
        put '/' => 'reviews#update'
    end

    get '/properties/:id' => 'properties#tenant_property', :as => 'previous_property'
  end
  
  resources :landlords, only: [:show, :edit] do
    resources :properties, only: [:edit, :update, :new, :create, :destroy]
    get '/properties' => 'properties#landlord_properties', :as => 'properties_show'
    get '/properties/:id' => 'properties#landlord_property', :as => 'property_show'
  end

  resources :landlords, only: [:show, :edit, :update]

  resources :properties, only: [:index, :show]
   post '/properties' => 'properties#filter_properties', :as => 'filter_properties'
   
  

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/property.rb
class Property < ApplicationRecord
    belongs_to :landlord
    belongs_to :tenant, optional: true
    has_many :previous_records, dependent: :destroy
    has_many :previous_tenants, through: :previous_records, source: :tenant, dependent: :destroy
    has_many :reviews, dependent: :destroy
    
    validates :address, :price, :description, presence: true
    validates :price, numericality: {only_integer: true} 

    scope :order_by_high_rating, -> {left_joins(:reviews).group(:id).order('avg(rating) desc')}
    scope :order_by_low_rating, -> {left_joins(:reviews).group(:id).order('avg(rating) asc')}
    scope :order_by_expensive, -> {order('price desc')}
    scope :order_by_cheap, -> {order('price asc')}

    def filter
    end

    def average_rating
        rating = []
        self.reviews.each do |review|
            rating << review.rating
        end
        if rating != []
           average_rating = rating.sum / rating.size
        else 
            average_rating = nil 
        end
        average_rating
    end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
    before_action :landlord_require_login, only: [:new, :create, :edit, :update, :destroy, :landlord_property, :landlord_properties]
    before_action :tenant_require_login, only: [:tenant_property]
    @@tenant_id

    def new
           @landlord = Landlord.find_by_id(params[:landlord_id])
           if landlord_authorized?(@landlord)
              @property = Property.new(landlord_id: params[:landlord_id])
              @available_tenants = Tenant.all.select {|tenant| !tenant.property}
              @url = landlord_properties_show_path
              render :new
           else 
            landlord_not_authorized
           end
    end

    def create
           @landlord = Landlord.find_by_id(params[:landlord_id])
            if landlord_authorized?(@landlord)
              @property = @landlord.properties.build(property_params)
              if @property.save
                  redirect_to landlord_property_show_path(@landlord, @property)
              else
                @available_tenants = Tenant.all.select {|tenant| !tenant.property}
                @url = landlord_properties_show_path
                render :new
              end
           else
            landlord_not_authorized
           end

    end

    def index
        if logged_in?
            if session[:filter_properties] == "Highest Rating"
               @properties = Property.order_by_high_rating.select {|property| !property.tenant}
            elsif session[:filter_properties] == "Lowest Rating"
                @properties = Property.order_by_low_rating.select {|property| !property.tenant}
            elsif session[:filter_properties] == "Cheapest"
               @properties = Property.order_by_cheap.select {|property| !property.tenant}
            elsif session[:filter_properties] == "Most Expensive"
                @properties = Property.order_by_expensive.select {|property| !property.tenant}
            else
                @properties = Property.all.select {|property| !property.tenant}
            end
           @property = Property.new
           @tenant = Tenant.find(session[:tenant_id]) if session[:tenant_id]
           @landlord = Landlord.find(session[:landlord_id]) if session[:landlord_id]
        else
           flash[:error] = "Please log in or sign up to view available properties!"
           redirect_to root_path
        end
    end

    def filter_properties
        session[:filter_properties] = params[:property][:filter] if params[:property][:filter]
        redirect_to properties_path
    end

    def show
        if logged_in?
          @property = Property.find(params[:id])
          property_exist?(@property)
          @reviews = Review.all.select {|review| review.property_id == @property.id}
        else
           flash[:error] = "Please log in or sign up to view the property!"
           redirect_to root_path
        end
    end

    def edit
           @landlord = Landlord.find_by_id(params[:landlord_id])
           @property = Property.find_by_id(params[:id])
           property_exist?(@property)
              if authorized_to_edit?(@property)
                  @available_tenants = Tenant.all.select {|tenant| !tenant.property} 
                  @@tenant_id = @property.tenant_id 
                  tenant = Tenant.find(@@tenant_id) if @@tenant_id
                  tenant ? @available_tenants << tenant : @available_tenants 
                  @url = landlord_property_show_path(@landlord, @property)
              else
                  flash[:error] = "Not authorized to edit this property!"
                  landlord_or_tenant_path
              end
 
    end

    

    def update
          @landlord = Landlord.find_by_id(params[:landlord_id])
          @property = Property.find_by_id(params[:id])
          property_exist?(@property)
            if authorized_to_edit?(@property)
              @previous_tenant = Tenant.find(@@tenant_id) if @@tenant_id
              @property.update(property_params)
                if  @@tenant_id && @@tenant_id != @property.tenant_id && !@property.previous_tenants.include?(@previous_tenant)
                  @property.previous_tenants << @previous_tenant
                  @property.save
                end
                redirect_to landlord_property_show_path(@landlord, @property)
             else
                flash[:error] = "Not authorized to edit this property!"
                landlord_or_tenant_path
             end
    end

    def landlord_properties
           @landlord = Landlord.find_by_id(params[:landlord_id])
           if landlord_authorized?(@landlord)
              @properties = @landlord.properties
           else
            landlord_not_authorized
           end
    end

    def landlord_property
          @landlord = Landlord.find_by_id(params[:landlord_id])
          @property = Property.find_by_id(params[:id])
          if authorized_to_edit?(@property)
             @reviews = Review.all.select {|review| review.property_id == @property.id}
          else
            landlord_not_authorized
          end
    end

    def tenant_property
           @tenant = Tenant.find_by_id(params[:tenant_id])
           if tenant_authorized?(@tenant)
              @property = Property.find_by_id(params[:id])
              if authorized_to_review?(@property)
                @review = Review.find_by(tenant_id: params[:tenant_id], property_id: params[:id])
                @reviews = Review.all.select {|review| review.property_id == @property.id}
              else
                flash[:error] = "Not authorzied to review this property"
                redirect_to property_path(@property)
              end
           else
              tenant_not_authorized
           end
    end

    def search
       @property =  Property.where("lower(address) LIKE ?", params[:query])
    end

  

    def destroy
           @landlord = Landlord.find_by_id(params[:landlord_id])
           @property = Property.find_by_id(params[:id])
           property_exist?(@property)
           if landlord_authorized?(@landlord) && authorized_to_edit?(@property)
              if @property.tenant
                  @property.tenant_id = nil
                  @property.save
              end
            @property.destroy
            flash[:message] = "Property deleted."
            redirect_to landlord_properties_show_path(@landlord)
           else
            landlord_not_authorized
           end
    end

    private
    def property_params
        params.require(:property).permit(:address, :price, :description, :image_url, :tenant_id)
    end

    def property_exist?(property)
        landlord_or_tenant_path if !property
    end   
    
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<div class="vh-100 img-container" style="padding-top: 120px;">

<div class="card text-lightpink bg-lightpink mb-3 m-auto" style="max-width: 25rem;">
<%= render partial: 'layouts/errors', locals: {obj: @property} %>

<% if !@property.id %>
  <div class="card-body"><h1>Add Property</h1></div>
<% else %>
  <div class="card-body"><h1>Edit Property</h1></div>
<% end %>
  <div class="card-body">
<%= form_for @property, url: @url  do |f| %>
    <%= f.label :address %><br>
    <%= f.text_field :address, :class => "border border-pink" %><br>
    <%= f.label :price %><br>
    <%= f.text_field :price, :class => "border border-pink" %><br>
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => "border border-pink" %><br>
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url, :class => "border border-pink" %><br>
    <%= f.label :tenant, "Current Tenant" %><br>
    <%= f.collection_select  :tenant_id, @available_tenants, :id, :name, {:include_blank => "No Tenant"}, {:class => "border border-pink"} %><br>
    
    <br />
  
    <%= f.submit :class => "text-decoration-none btn btn-outline-dark"  %>
  <% end %>
  <br>
    
  <% if !@property.id %>
     <p><%= link_to '<<', landlord_properties_show_path(@landlord), :class => 'back' %></p>
  <% else %>
     <p><%= link_to '<<', landlord_property_show_path(@landlord, @property), :class => 'back' %></p>
  <% end %>
</div>
</div>
</div>

app/views/properties/edit.html.erb
<%= render 'form' %>

app/views/properties/index.html.erb
<nav style="background-color: darkcyan;">
            <div class="nav justify-content-between p-2">
               <h2 class='pt-3 pl-3' style='color: white; font-size: 20px;'>All Available Properties</h2>
            </div>
        
</nav>

<%= form_with url: search_properties_path, method: :get do |form| %>
  <%= form.label :query, "Search for:" %>
  <%= form.text_field :query %>
  <%= form.submit "Search" %>
<% end %>


  <div class='pt-3 pl-3'> 
   <%= form_for @property do |f| %>
     <%= f.select :filter, ['Highest Rating', 'Lowest Rating', 'Cheapest', 'Most Expensive'], {:prompt => 'Pick a filter option'}, {:class => "border border-pink text-pink"} %>
     <%= f.submit 'Submit', :class => "text-decoration-none btn btn-outline-dark ml-2 p-1"  %>
   <% end %>

   <div class='pt-3'>
   
   <% @properties.each do |property| %>
    
    <div class="card .h-100 mb-4" style="width: 18rem; background-color: lightseagreen;">
     <p><%= image_tag  property.image_url,  height: '200', width: '200', :class => "card-img-top" %></p>
     <div class="card-body">
     <p class="card-title font-weight-bold"><%= property.address%>- £<%=property.price%>pcm</p>
      <%if property.average_rating %>
        <p class="card-text">Rating: <%= property.average_rating %>/5</p>
      <% end %>
     <p><%= link_to "Click here for more info", property_path(property), :class => "back" %></p>
     
     </div>
     </div>
   <% end %>



   <% if @tenant %>
   <p><%= link_to '<<', tenant_path(@tenant), :class => "back" %></p>
   <% end %>
   <% if @landlord %>
   <p><%= link_to '<<', landlord_path(@landlord), :class => "back"%></p>
   <% end %>
 
   </div>
   </div>

   
  

app/views/properties/landlord_properties.html.erb
<nav style="background-color: darkcyan;">
            <ul class="nav justify-content-between p-2">
               <li class='pt-3 pl-3' style='color: white; font-size: 20px;'>All of Your Properties</li>
              <li class='nav-link'><%= link_to "Add New Property", new_landlord_property_path(@landlord), class: 'nav-link' %></li>
            </ul>
        
</nav>

<div class= "p-3">
<% @properties.each do |property| %>
  <div class="card .h-100 mb-4" style="width: 18rem; background-color: lightseagreen;">
  <p><%= image_tag  property.image_url,  height: '200', width: '200', :class => "card-img-top" %></p>
     <div class="card-body">
     <p class="card-title font-weight-bold"><%= property.address%>- £<%=property.price%>pcm</p>
     <%if property.average_rating %>
       <p class="card-text">Rating: <%= property.average_rating %>/5</p> 
       <% end %>
     <p><%= link_to "Click here for more info", landlord_property_path(@landlord, property), :class => "back" %></p>
     
     </div>
     </div>
   <% end %>

<h3></h3>
<p><%= link_to '<<', landlord_path(@landlord), :class => "back" %></p>
</div>

app/views/properties/landlord_property.html.erb
<nav style="background-color: darkcyan;">
            <ul class="nav justify-content-end p-2">
              <li class='nav-link'><%= link_to "Edit Property", edit_landlord_property_path(@landlord, @property), class: 'nav-link' %></li>
              <li class='nav-link'><%= link_to "Delete Property", landlord_property_path(@landlord, @property), method: :delete, class: 'nav-link' %></li>
            </ul>
        
</nav>
<div class='pl-3 mt-n5'>
<h2><%= @property.address %></h2>
<div class='pt-2'>
<p><%= image_tag  @property.image_url,  maxHeight: '80%%', maxWidth: '80%', :class => 'mt-3'  %></p>
<p><b>Price:</b> £<%= @property.price %>pcm</p>
<p><b>Description:</b> <%= @property.description %></p>
<% if @property.tenant %>
   <p><b>Current Tenant:</b> <%= @property.tenant.user.name %> - Contact info: <%= @property.tenant.user.email %></p>
<% end %>
<% if !@property.previous_tenants.empty? %>
   <p><b>Previous Tenants:</b></p>
   <ul>
     <% @property.previous_tenants.each do |tenant| %>
      <li><%= tenant.user.name %> - Contact info: <%= tenant.user.email %></li>
  <% end %>
   </ul>
<% end %>
<% if !@reviews.empty? %>
  <p><b>Reviews:</b></p>
  <ol>
    <% @reviews.each do |review| %>
      <li><ul>
            <li>Rating: <%= review.rating %></li>
            <li>Title: <%= review.title %></li>
            <li>Content: <%= review.content %></li>
            <li>Reviewed by: <%= review.tenant.user.name %></li>
      </li></ul><br>
    <% end %>
  </ol>
<% end %>

<p><%= link_to '<<', landlord_properties_show_path(@landlord), :class => 'back' %></p>

</div>

app/views/properties/landlord_property_show.html.erb
<h1> <%= @property.address %> </h1>
<p><%= image_tag  @property.image_url,  maxHeight: '50%', maxWidth: '50%' %></p>
<p>Price:<%= @property.price %><p>
<p>Description:<%= @property.description %><p>
<p>Edit Property</p>
<p>Delete Property</p>

app/views/properties/new.html.erb
<%= render 'form' %>

app/views/properties/show.html.erb
<nav style="background-color: darkcyan;">
            <ul class="nav p-3">
              <li class='pt-3' style='color: white; font-size: 20px; '><h2><%= @property.address %></h2></li>
            </ul>
        
</nav>
<div class='pl-3 pt-3'>
<p><%= image_tag  @property.image_url,  maxHeight: '80%', maxWidth: '80%' %></p>
<p><b>Price:</b> £<%= @property.price %>pcm<p>
<p><b>Description:</b> <%= @property.description %><p>
<p>If interested, please contact <b><%= @property.landlord.user.name %> at <%= @property.landlord.user.email %>!</b></p>

<% if !@reviews.empty? %>
  <p><b>Reviews:</b></p>
  <ol>
    <% @reviews.each do |review| %>
      <li><ul>
            <li>Stars: <%= review.rating %>/5</li>
            <li>Title: <%= review.title %></li>
            <li>Content: <%= review.content %></li>
            <li>Reviewed by: <%= review.tenant.user.name %></li>
      </li></ul><br>
    <% end %>
  </ol>
<% end %>
<p><%= link_to '<<', properties_path, :class => 'back' %></p>
</div>

app/views/properties/tenant_property.html.erb
<nav style="background-color: darkcyan;">
          <ul class="nav justify-content-end p-2">
               <% if !@review %>
                <li class='nav-link'><%= link_to "Leave a Review", new_tenant_property_review_path(@tenant, @property), class: 'nav-link' %></li>
                </ul>
              <% else %>
              
                <li class='nav-link'><%= link_to "Edit Review", edit_tenant_property_review_path(@tenant, @property, @review), class: 'nav-link' %></li>
                <li class='nav-link'><%= link_to "Delete Review", tenant_property_review_path(@tenant, @property, @review), method: :delete, class: 'nav-link' %></li>
                </ul>
              <% end %>
           
        
</nav>

<div class='pl-3 mt-n5'>
<h2><%= @property.address %></h2>
<div class='pt-3'>
<p><%= image_tag  @property.image_url,  maxHeight: '50%', maxWidth: '50%' %></p>
<p><b>Price:</b> £<%= @property.price %>pcm<p>
<p><b>Description:</b> <%= @property.description %><p>

<% if @reviews %>
   <p><b>Reviews:</b></p>
  <ol>
    <% @reviews.each do |review| %>
      <li><ul>
            <li>Stars: <%= review.rating %>/5</li>
            <li>Title: <%= review.title %></li>
            <li>Content: <%= review.content %></li>
            <li>Reviewed by: <%= review.tenant.user.name %></li>
      </li></ul><br>
    <% end %>
  </ol>
<% end %>

<p><%= link_to "<<", tenant_path(@tenant), :class => 'back' %></p>
</div>
</div>